-- ----------------------------------------------------------------------
-- MySQL Migration Toolkit
-- SQL Create Script
-- ----------------------------------------------------------------------

SET FOREIGN_KEY_CHECKS = 0;

CREATE DATABASE IF NOT EXISTS `CONSULTAS`
  CHARACTER SET latin1 COLLATE latin1_swedish_ci;
-- -------------------------------------
-- Tables

DROP TABLE IF EXISTS `CONSULTAS`.`buscar museo arqueologico de huichapan`;
CREATE TABLE `CONSULTAS`.`buscar museo arqueologico de huichapan` (
  `NI` DOUBLE(15, 5) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`buscar1`;
CREATE TABLE `CONSULTAS`.`buscar1` (
  `NI` DOUBLE(15, 5) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`CATÁLOGO DE MUSEOS`;
CREATE TABLE `CONSULTAS`.`CATÁLOGO DE MUSEOS` (
  `Número de contrato` SMALLINT(5) NULL,
  `Entidad` VARCHAR(23) NULL,
  `Clave de Museo` SMALLINT(5) NULL,
  `Nombre de Museo` VARCHAR(100) NULL,
  `Direccion` VARCHAR(200) NULL,
  `Director` VARCHAR(50) NULL,
  `Cargo` VARCHAR(10) NULL,
  PRIMARY KEY (`Clave de Museo`),
  INDEX `Entidad` (`Entidad`),
  INDEX `Número de contrato` (`Número de contrato`)
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`COMODATO MUSEO DEL BARRO`;
CREATE TABLE `CONSULTAS`.`COMODATO MUSEO DEL BARRO` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`consulta florencia`;
CREATE TABLE `CONSULTAS`.`consulta florencia` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`CONSULTA_AGUSTINOS`;
CREATE TABLE `CONSULTAS`.`CONSULTA_AGUSTINOS` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`Errores de pegado`;
CREATE TABLE `CONSULTAS`.`Errores de pegado` (
  `F1` DOUBLE(15, 5) NULL,
  `F2` VARCHAR(255) NULL,
  `F3` DOUBLE(15, 5) NULL,
  `F4` DOUBLE(15, 5) NULL,
  `F5` VARCHAR(255) NULL,
  `F6` VARCHAR(255) NULL,
  `F7` VARCHAR(255) NULL,
  `F8` VARCHAR(255) NULL,
  `F9` VARCHAR(255) NULL,
  `F10` VARCHAR(255) NULL,
  `F11` VARCHAR(255) NULL,
  `F12` VARCHAR(255) NULL,
  `F13` VARCHAR(255) NULL,
  `F14` VARCHAR(255) NULL,
  `F15` VARCHAR(255) NULL,
  `F16` VARCHAR(255) NULL,
  `F17` VARCHAR(255) NULL,
  `F18` VARCHAR(255) NULL,
  `F19` VARCHAR(255) NULL,
  `F20` VARCHAR(255) NULL,
  `F21` VARCHAR(255) NULL,
  `F22` VARCHAR(255) NULL,
  `F23` VARCHAR(255) NULL,
  `F24` VARCHAR(255) NULL,
  `F25` VARCHAR(255) NULL,
  `F26` VARCHAR(255) NULL,
  `F27` VARCHAR(255) NULL,
  `F28` VARCHAR(255) NULL,
  `F29` VARCHAR(255) NULL,
  `F30` DOUBLE(15, 5) NULL,
  `F31` VARCHAR(255) NULL,
  `F32` VARCHAR(255) NULL,
  `F33` VARCHAR(255) NULL,
  `F34` VARCHAR(255) NULL,
  `F35` DATETIME NULL,
  `F36` VARCHAR(255) NULL,
  `F37` VARCHAR(255) NULL,
  `F38` VARCHAR(255) NULL,
  `F39` VARCHAR(255) NULL,
  `F40` DATETIME NULL,
  `F41` VARCHAR(255) NULL,
  `F42` VARCHAR(255) NULL,
  `F43` VARCHAR(255) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`FICHAS`;
CREATE TABLE `CONSULTAS`.`FICHAS` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`Número de inventario`),
  INDEX `Clave de Museo` (`Clave de Museo`),
  INDEX `NI` (`NI`),
  INDEX `Número de catálogo` (`Número de catálogo`),
  INDEX `Número de registro` (`Número de registro`),
  INDEX `Pieza` (`Pieza`)
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`FICHAS Dolores Hidalgo`;
CREATE TABLE `CONSULTAS`.`FICHAS Dolores Hidalgo` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`Número de inventario`),
  INDEX `Clave de Museo` (`Clave de Museo`),
  INDEX `NI` (`NI`),
  INDEX `Número de catálogo` (`Número de catálogo`),
  INDEX `Número de registro` (`Número de registro`),
  INDEX `Pieza` (`Pieza`)
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`fichas enah`;
CREATE TABLE `CONSULTAS`.`fichas enah` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`FICHAS HISTORIA MEXICANA`;
CREATE TABLE `CONSULTAS`.`FICHAS HISTORIA MEXICANA` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL,
  INDEX `Clave de Museo` (`Clave de Museo`),
  INDEX `Número de catálogo` (`Número de catálogo`),
  INDEX `Número de inventario` (`Número de inventario`),
  INDEX `Número de registro` (`Número de registro`)
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`fichas medidas granos`;
CREATE TABLE `CONSULTAS`.`fichas medidas granos` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`FICHAS METAL`;
CREATE TABLE `CONSULTAS`.`FICHAS METAL` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`FICHAS MUSEO REGIONAL DE QUERÉTARO`;
CREATE TABLE `CONSULTAS`.`FICHAS MUSEO REGIONAL DE QUERÉTARO` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL,
  INDEX `Clave de Museo` (`Clave de Museo`),
  INDEX `Número de catálogo` (`Número de catálogo`),
  INDEX `Número de inventario` (`Número de inventario`),
  INDEX `Número de registro` (`Número de registro`)
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`FICHAS Tlal`;
CREATE TABLE `CONSULTAS`.`FICHAS Tlal` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL,
  INDEX `Clave de Museo` (`Clave de Museo`),
  INDEX `Número de catálogo` (`Número de catálogo`),
  INDEX `Número de inventario` (`Número de inventario`),
  INDEX `Número de registro` (`Número de registro`)
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`FICHAS_anterior_10062015`;
CREATE TABLE `CONSULTAS`.`FICHAS_anterior_10062015` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`Número de inventario`),
  INDEX `Clave de Museo` (`Clave de Museo`),
  INDEX `NI` (`NI`),
  INDEX `Número de catálogo` (`Número de catálogo`),
  INDEX `Número de registro` (`Número de registro`),
  INDEX `Pieza` (`Pieza`)
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`FICHAS_ErroresDeExportación`;
CREATE TABLE `CONSULTAS`.`FICHAS_ErroresDeExportación` (
  `Campo` VARCHAR(255) NULL,
  `Error` VARCHAR(255) NULL,
  `Fila` INT(10) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`fichascopia totales`;
CREATE TABLE `CONSULTAS`.`fichascopia totales` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`FICHASmrtAS`;
CREATE TABLE `CONSULTAS`.`FICHASmrtAS` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Nombre de Museo` VARCHAR(100) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`FICHASnuevas`;
CREATE TABLE `CONSULTAS`.`FICHASnuevas` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`Número de inventario`),
  INDEX `Clave de Museo` (`Clave de Museo`),
  INDEX `NI` (`NI`),
  INDEX `Número de catálogo` (`Número de catálogo`),
  INDEX `Número de registro` (`Número de registro`),
  INDEX `Pieza` (`Pieza`)
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`fichasTLAX`;
CREATE TABLE `CONSULTAS`.`fichasTLAX` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`frias`;
CREATE TABLE `CONSULTAS`.`frias` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`INAH1 ORIGINAL ACTUAL original`;
CREATE TABLE `CONSULTAS`.`INAH1 ORIGINAL ACTUAL original` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`Número de inventario`),
  INDEX `Clave de Museo` (`Clave de Museo`),
  INDEX `NI` (`NI`),
  INDEX `Número de catálogo` (`Número de catálogo`),
  INDEX `Número de registro` (`Número de registro`),
  INDEX `Pieza` (`Pieza`)
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`MUSEO DE SITIO DE CHOLULA`;
CREATE TABLE `CONSULTAS`.`MUSEO DE SITIO DE CHOLULA` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`museo regional de guerrero`;
CREATE TABLE `CONSULTAS`.`museo regional de guerrero` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`MUSEO REGIONAL DE NAYARIT`;
CREATE TABLE `CONSULTAS`.`MUSEO REGIONAL DE NAYARIT` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL,
  INDEX `Clave de Museo` (`Clave de Museo`),
  INDEX `Número de catálogo` (`Número de catálogo`),
  INDEX `Número de inventario` (`Número de inventario`),
  INDEX `Número de registro` (`Número de registro`)
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`MUSEO REGIONAL DE PUEBLA`;
CREATE TABLE `CONSULTAS`.`MUSEO REGIONAL DE PUEBLA` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`MUSEO SAN MIGUEL DE ALLENDE`;
CREATE TABLE `CONSULTAS`.`MUSEO SAN MIGUEL DE ALLENDE` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`PIEZAS PRESTADAS AL MUSEO DEL VIDRIO`;
CREATE TABLE `CONSULTAS`.`PIEZAS PRESTADAS AL MUSEO DEL VIDRIO` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`PUEBLA`;
CREATE TABLE `CONSULTAS`.`PUEBLA` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL,
  INDEX `Clave de Museo` (`Clave de Museo`),
  INDEX `Número de catálogo` (`Número de catálogo`),
  INDEX `Número de inventario` (`Número de inventario`),
  INDEX `Número de registro` (`Número de registro`)
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`SEXUALIDAD FICHAS`;
CREATE TABLE `CONSULTAS`.`SEXUALIDAD FICHAS` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`SIN NUMERO INAH-HISTORIA MEXICANA`;
CREATE TABLE `CONSULTAS`.`SIN NUMERO INAH-HISTORIA MEXICANA` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`tlaxcala impreso de la tecnica`;
CREATE TABLE `CONSULTAS`.`tlaxcala impreso de la tecnica` (
  `Contador` INT(10) NOT NULL AUTO_INCREMENT,
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`Contador`),
  INDEX `Clave de Museo` (`Clave de Museo`),
  INDEX `Número de catálogo` (`Número de catálogo`),
  INDEX `Número de inventario` (`Número de inventario`),
  INDEX `Número de registro` (`Número de registro`)
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CONSULTAS`.`TLAXHIST`;
CREATE TABLE `CONSULTAS`.`TLAXHIST` (
  `Clave de Museo` SMALLINT(5) NULL,
  `Número de inventario` VARCHAR(20) NULL,
  `NI` INT(10) NULL,
  `Pieza` SMALLINT(5) NULL,
  `Pzas` SMALLINT(5) NULL,
  `Piezas` SMALLINT(5) NULL,
  `Otros números` VARCHAR(150) NULL,
  `Número de catálogo` VARCHAR(100) NULL,
  `Número de registro` VARCHAR(100) NULL,
  `Tipo de objeto` VARCHAR(250) NULL,
  `Nombre o tema` VARCHAR(250) NULL,
  `Autor` VARCHAR(255) NULL,
  `Materia prima` VARCHAR(255) NULL,
  `Forma` VARCHAR(255) NULL,
  `Técnica de manufactura` VARCHAR(255) NULL,
  `Técnica decorativa` VARCHAR(255) NULL,
  `Inscripciones` LONGTEXT NULL,
  `Marca` VARCHAR(100) NULL,
  `Cultura` VARCHAR(255) NULL,
  `Epoca` VARCHAR(255) NULL,
  `Origen` VARCHAR(255) NULL,
  `Procedencia` VARCHAR(255) NULL,
  `Adquisición` VARCHAR(255) NULL,
  `Ubicación` VARCHAR(255) NULL,
  `Estado de conservación` TINYINT(3) UNSIGNED NULL,
  `Observaciones` LONGTEXT NULL,
  `Largo/alto` DOUBLE(15, 5) NULL,
  `Ancho` DOUBLE(15, 5) NULL,
  `Espesor` DOUBLE(15, 5) NULL,
  `Diámetro` DOUBLE(15, 5) NULL,
  `Importancia del bien` VARCHAR(1) NULL,
  `Curaduría` VARCHAR(50) NULL,
  `Inventarió` VARCHAR(100) NULL,
  `Capturó` VARCHAR(20) NULL,
  `Depuró` VARCHAR(20) NULL,
  `Fecha` DATETIME NULL,
  `Movimientos` LONGTEXT NULL,
  `Avalúo` INT(10) NULL,
  `Acervo` VARCHAR(14) NULL,
  `Status` VARCHAR(50) NULL,
  `Fecha de integración` DATETIME NULL,
  `Carpeta` TINYINT(1) NOT NULL,
  `Depurado` TINYINT(1) NOT NULL,
  `Archivo de imagen` VARCHAR(100) NULL,
  INDEX `Clave de Museo` (`Clave de Museo`),
  INDEX `Número de catálogo` (`Número de catálogo`),
  INDEX `Número de inventario` (`Número de inventario`),
  INDEX `Número de registro` (`Número de registro`)
)
ENGINE = INNODB;



SET FOREIGN_KEY_CHECKS = 1;

-- ----------------------------------------------------------------------
-- EOF

